language: python

stages:
  - linting
  - test

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"
    - "$HOME/.cache/pre-commit"

install:
  - pip install -U pip
  - python setup.py install
  - pip install -r requirements.txt
  - pip install -e .
  - pip install travis

script: travis wait python -m pytest --pyargs tests negmas negmas/tests
